name: Release

on:
    push:
        tags:
          - 'v*'

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        env:
            RELEASE_TITLE: 'Перевод курсов ${{ github.ref_name}}'
            BUILD_DIRECTORY: 'build'
        steps:
            - uses: actions/checkout@v3
            - name: Pull Containers
              run: |
                docker pull asciidoctor/docker-asciidoctor:latest
                docker pull pandoc/core:latest
            - name: Build all courses with AsciiDoctor
              run: |
                docker run \
                    --rm -v '${{ github.workspace }}':/documents \
                    asciidoctor/docker-asciidoctor \
                    ./scripts/build_all.sh -o '${{ env.BUILD_DIRECTORY }}' -s '${{ github.ref_name}}' -c asciidoctor
            - name: Build all courses with Pandoc
              run: |
                docker run \
                    --rm -v '${{ github.workspace }}':/documents \
                    pandoc/core \
                    ./scripts/build_all.sh -o '${{ env.BUILD_DIRECTORY }}' -s '${{ github.ref_name}}' -c pandoc
            - name: Release all courses assets
              run: |
                ./scripts/release_all.sh '${{ github.ref_name}}' \
                    -o '${{ env.BUILD_DIRECTORY }}' \
                    -s '${{ github.ref_name}}' \
                    '${{ env.RELEASE_TITLE }}'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
