name: Release

on:
    push:
        tags:
          - 'v*'

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        env:
            RELEASE_TITLE: 'Перевод курсов ${{ github.ref_name}}'
            BUILD_DIRECTORY: 'build'
        steps:
            - uses: actions/checkout@v3
            - name: Build all courses
              run: |
                docker run \
                    --rm -v '${{ github.workspace }}':/documents \
                    asciidoctor/docker-asciidoctor:latest \
                    /bin/sh -cx "apk add --no-cache pandoc; \
                    ./scripts/build_all.sh -o '${{ env.BUILD_DIRECTORY }}' -s '${{ github.ref_name}}'"
            - name: Release all courses assets
              run: |
                bash -x ./scripts/release_all.sh '${{ github.ref_name}}' \
                    -o '${{ env.BUILD_DIRECTORY }}' \
                    -s '${{ github.ref_name}}' \
                    '${{ env.RELEASE_TITLE }}'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
