name: Release

on:
    push:
        tags:
          - 'v*'

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        env:
            RESULT_NAME: 'Инструментарий_и_компиляторные_оптимизации_для_RISC-V_(LFD113x)_RU_${{ github.ref_name}}'
        steps:
            - uses: actions/checkout@v3
            - name: Pull Container
              run: |
                docker pull asciidoctor/docker-asciidoctor:latest
            - name: Build pdf
              run: |
                docker run \
                    --rm -v '${{ github.workspace }}':/documents \
                    asciidoctor/docker-asciidoctor \
                    make RESULT_PDF=${{ env.RESULT_NAME }}.pdf
            - name: Release
              run: |
                gh release create ${{ github.ref_name}} -t '${{ env.NAME }}' '${{ env.RESULT_NAME }}.pdf'
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NAME: 'Перевод курса "RISC-V Toolchain and Compiler Optimization Techniques" (LFD113x) ${{ github.ref_name}}'
