name: Release

on:
    push:
        tags:
          - 'v*'

permissions:
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        env:
            RESULT_PDF: Course.pdf
        steps:
            - uses: actions/checkout@v3
            - name: Pull Container
              run: |
                docker pull asciidoctor/docker-asciidoctor:latest
            - name: Build pdf
              run: |
                docker run --rm -v "${{ github.workspace }}":/documents asciidoctor/docker-asciidoctor make
            - uses: actions/upload-artifact@v3
              with:
                name: Course
                path: ${{ env.RESULT_PDF }}
                if-no-files-found: error
            - name: Release
              run: |
                gh release create ${{ github.ref_name}} -t "${{ env.NAME }}" ${{ env.RESULT_PDF }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NAME: "${{ github.ref_name}} RISC-V Toolchain and Compiler Optimization Techniques (LFD113x)"
